Feat/menu-navigation
bitcoinsearch/tldr pull request #104
Opened 2023-11-21 15:20 UTC by IgboPharaoh

WIP

2023-11-30 15:06 UTC, adamjonas commented on src/app/components/server/newsletter.tsx
> +          <h2 className='text-xl md:text-4xl font-normal pb-8 pt-10'>Summary of Newsletters </h2>
```suggestion
          <h2 className='text-xl md:text-4xl font-normal pb-8 pt-10'>Summary</h2>
```

2023-11-30 15:06 UTC, adamjonas commented on src/app/components/server/newsletter.tsx
> +          <h2 className='text-xl md:text-4xl font-normal pb-8 pt-10'>New posts this week</h2>
```suggestion
          <h2 className='text-xl md:text-4xl font-normal pb-8 pt-10'>New posts</h2>
```

2023-11-30 15:07 UTC, adamjonas commented on src/app/components/server/newsletter.tsx
> +          <h2 className='text-xl md:text-4xl font-normal pb-8 pt-10'>Active posts this week</h2>
```suggestion
          <h2 className='text-xl md:text-4xl font-normal pb-8 pt-10'>Ongoing Discussions</h2>
```

2023-11-30 15:08 UTC, adamjonas commented
The newsletter page should look more like the landing page but we can handle that in a follow up post.

2023-11-30 15:09 UTC, IgboPharaoh commented
> Mobile looks good
> 
> Why does the rss feed link trigger a download?

I've tried to replicate the rss issue on my end and I've not been able to even after testing with the latest deployment. Please can you outline the steps you took to arrive at this issue?

2023-11-30 20:16 UTC, adamjonas commented
I just navigated to the rss feed on my phone. Not a blocker if no one else is running into it.

2023-11-30 20:17 UTC, adamjonas commented
let's get code review from @Extheoisah or @Emmanuel-Develops so we can 🚢 it

2023-12-01 03:57 UTC, IgboPharaoh commented
> I just navigated to the rss feed on my phone. Not a blocker if no one else is running into it.

Alright

2023-12-02 09:36 UTC, Emmanuel-Develops requested changes

2023-12-02 09:36 UTC, Emmanuel-Develops commented on src/app/components/client/homepage.tsx
> +        {/* <section>
please remove unneeded commented-out code

2023-12-02 09:36 UTC, Emmanuel-Develops commented on src/app/components/client/navigation-menu.tsx
> +              {/* <LinkComponent title='Today in Bitcoin/LN History' href='/#today_in_history' /> */}
same here

2023-12-02 09:36 UTC, Emmanuel-Develops commented on src/app/newsletter/page.tsx
> +              <div key={`${index}_${set.week_0.link}`}>
any reason we are showing only the first two entries `week_0` and `week_1`

for example, the november newsletter set has 4 newsletter entries

2023-12-03 03:01 UTC, igbopharaoh commented on src/app/components/client/homepage.tsx
> +        {/* <section>
this is for the sections Urvish is working on but hasn't been completed yet

2023-12-03 03:01 UTC, igbopharaoh commented on src/app/components/client/navigation-menu.tsx
> +              {/* <LinkComponent title='Today in Bitcoin/LN History' href='/#today_in_history' /> */}
this is for the sections Urvish is working on but hasn't been completed yet

2023-12-03 10:20 UTC, Extheoisah commented
There's a hydration mismatch error when I run the code
![image](https://github.com/bitcoinsearch/tldr/assets/60826700/3350e9d9-1e18-4fe8-8635-62f673aefaa9)

There's another warning about updating the nextjs version because the one we have is outdated.
I have rebased and updated the static folder causing the conflict.

2023-12-03 10:25 UTC, Extheoisah commented
> There's a hydration mismatch error when I run the code ![image](https://private-user-images.githubusercontent.com/60826700/287510326-3350e9d9-1e18-4fe8-8635-62f673aefaa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1OTkzNDksIm5iZiI6MTcwMTU5OTA0OSwicGF0aCI6Ii82MDgyNjcwMC8yODc1MTAzMjYtMzM1MGU5ZDktMWUxOC00ZmU4LTg2MzUtNjJmNjczYWVmYWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDEwMjQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZTQ0NzY5NzMwOTM4MzE0OWFmZGZiNmQ4ZDEzYjkzZjViYzhkZmUwYjQxYTNhMjk4NmUxNGRhYjAwNmEwYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5XHj8HIImXVeGBIrhXn6V2FKi6nrVyX1tjTsr5ysTRk)
> 
> There's another warning about updating the nextjs version because the one we have is outdated. I have rebased and updated the static folder causing the conflict.

I'll raise another pr to update nextjs. This hydration error is non-blocking by the way. We can merge.

2023-12-05 15:44 UTC, merged